<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325172600 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(120) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_exercise_slug ON exercise (slug)');
        $this->addSql('CREATE TABLE exercise_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, title VARCHAR(200) NOT NULL, description TEXT NOT NULL, short_description VARCHAR(500) NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F99B55EBE934951A ON exercise_translation (exercise_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_exercise_locale ON exercise_translation (exercise_id, locale)');
        $this->addSql('ALTER TABLE exercise_translation ADD CONSTRAINT FK_F99B55EBE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_translation DROP CONSTRAINT FK_F99B55EBE934951A');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE exercise_translation');
    }
}
