<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260501100512 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE deck (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, cards_count INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE deck_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, deck_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F8F58FCC111948DC ON deck_translation (deck_id)');
        $this->addSql('ALTER TABLE deck_translation ADD CONSTRAINT FK_F8F58FCC111948DC FOREIGN KEY (deck_id) REFERENCES deck (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deck_translation DROP CONSTRAINT FK_F8F58FCC111948DC');
        $this->addSql('DROP TABLE deck');
        $this->addSql('DROP TABLE deck_translation');
    }
}
