<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260629122529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE psychological_state (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(120) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_psychological_state_slug ON psychological_state (slug)');
        $this->addSql('CREATE TABLE psychological_state_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, title VARCHAR(200) NOT NULL, psychological_state_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9DA2A6498A7A49C2 ON psychological_state_translation (psychological_state_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_psychological_state_locale ON psychological_state_translation (psychological_state_id, locale)');
        $this->addSql('ALTER TABLE psychological_state_translation ADD CONSTRAINT FK_9DA2A6498A7A49C2 FOREIGN KEY (psychological_state_id) REFERENCES psychological_state (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE psychological_state_translation DROP CONSTRAINT FK_9DA2A6498A7A49C2');
        $this->addSql('DROP TABLE psychological_state');
        $this->addSql('DROP TABLE psychological_state_translation');
    }
}
