<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612105352 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE spread (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE spread_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, spread_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8FE750C229AF074E ON spread_card (spread_id)');
        $this->addSql('CREATE TABLE spread_card_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, title VARCHAR(255) NOT NULL, spread_card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4227B5AC70BFAD1E ON spread_card_translation (spread_card_id)');
        $this->addSql('ALTER TABLE spread_card ADD CONSTRAINT FK_8FE750C229AF074E FOREIGN KEY (spread_id) REFERENCES spread (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE spread_card_translation ADD CONSTRAINT FK_4227B5AC70BFAD1E FOREIGN KEY (spread_card_id) REFERENCES spread_card (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE spread_card DROP CONSTRAINT FK_8FE750C229AF074E');
        $this->addSql('ALTER TABLE spread_card_translation DROP CONSTRAINT FK_4227B5AC70BFAD1E');
        $this->addSql('DROP TABLE spread');
        $this->addSql('DROP TABLE spread_card');
        $this->addSql('DROP TABLE spread_card_translation');
    }
}
